#pragma once

enum UNIFORM_TYPE
{
    U_MVP = 0,
    U_MODELVIEW,
    U_MODELVIEW_INVERSE_TRANSPOSE,
    U_MATERIAL_AMBIENT,
    U_MATERIAL_DIFFUSE,
    U_MATERIAL_SPECULAR,
    U_MATERIAL_SHININESS,

    U_NUMLIGHTS,
    U_LIGHT0_POSITION,
    U_LIGHT0_TYPE,
    U_LIGHT0_COLOR,
    U_LIGHT0_POWER,
    U_LIGHT0_KC,
    U_LIGHT0_KL,
    U_LIGHT0_KQ,
    U_LIGHT0_COSCUTOFF,
    U_LIGHT0_COSINNER,
    U_LIGHT0_EXPONENT,
    U_LIGHT0_SPOTDIRECTION,

    U_LIGHTENABLED,
    U_COLOR_TEXTURE_ENABLED,
    U_COLOR_TEXTURE,
    U_TEXT_ENABLED,
    U_TEXT_COLOR,
    U_TOTAL,
};